-- CREACIÓN DE BD Y TABLAS


-- MySQL Script generated by MySQL Workbench
-- Thu Jun 20 08:57:31 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS,
    UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS,
    FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE,
    SQL_MODE = 'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';


-- -----------------------------------------------------
-- Schema bs3o8whqnfg4fgedo5fk
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bs3o8whqnfg4fgedo5fk
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bs3o8whqnfg4fgedo5fk` DEFAULT CHARACTER SET utf8mb4;
USE `bs3o8whqnfg4fgedo5fk`;


-- -----------------------------------------------------
-- Table `bs3o8whqnfg4fgedo5fk`.`tipos_documentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bs3o8whqnfg4fgedo5fk`.`tipos_documentos` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `nombre` VARCHAR(45) NOT NULL,
    `abreviatura` VARCHAR(5) NOT NULL,
    PRIMARY KEY (`id`)
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bs3o8whqnfg4fgedo5fk`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bs3o8whqnfg4fgedo5fk`.`roles` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `nombre` VARCHAR(45) NOT NULL,
    PRIMARY KEY (`id`)
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bs3o8whqnfg4fgedo5fk`.`jornadas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bs3o8whqnfg4fgedo5fk`.`jornadas` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `nombre` VARCHAR(45) NOT NULL,
    `hora_inicio` TIME NOT NULL,
    `hora_fin` TIME NOT NULL,
    PRIMARY KEY (`id`)
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bs3o8whqnfg4fgedo5fk`.`asignaturas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bs3o8whqnfg4fgedo5fk`.`asignaturas` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `nombre` VARCHAR(45) NOT NULL,
    PRIMARY KEY (`id`)
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bs3o8whqnfg4fgedo5fk`.`empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bs3o8whqnfg4fgedo5fk`.`empleados` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `nombre` VARCHAR(45) NOT NULL,
    `apellido` VARCHAR(45) NOT NULL,
    `salario` DECIMAL(10) NOT NULL,
    `correo_electronico` VARCHAR(60) NOT NULL,
    `tipos_documentos_id` INT NOT NULL,
    `numero_documento` VARCHAR(45) NOT NULL,
    `fecha_nacimiento` DATE NOT NULL,
    `roles_id` INT NOT NULL,
    PRIMARY KEY (`id`, `tipos_documentos_id`, `roles_id`),
    INDEX `fk_empleados_roles1_idx` (`roles_id` ASC) VISIBLE,
    INDEX `fk_empleados_tipos_documentos1_idx` (`tipos_documentos_id` ASC) VISIBLE,
    UNIQUE INDEX `numero_documento_UNIQUE` (`numero_documento` ASC) VISIBLE,
    CONSTRAINT `fk_empleados_roles1` FOREIGN KEY (`roles_id`) REFERENCES `bs3o8whqnfg4fgedo5fk`.`roles` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_empleados_tipos_documentos1` FOREIGN KEY (`tipos_documentos_id`) REFERENCES `bs3o8whqnfg4fgedo5fk`.`tipos_documentos` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bs3o8whqnfg4fgedo5fk`.`cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bs3o8whqnfg4fgedo5fk`.`cursos` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `nombre` VARCHAR(45) NOT NULL,
    `profesor_encargado_id` INT NOT NULL,
    `jornadas_id` INT NOT NULL,
    PRIMARY KEY (`id`, `profesor_encargado_id`, `jornadas_id`),
    INDEX `fk_cursos_empleados1_idx` (`profesor_encargado_id` ASC) VISIBLE,
    INDEX `fk_cursos_jornadas1_idx` (`jornadas_id` ASC) VISIBLE,
    CONSTRAINT `fk_cursos_empleados1` FOREIGN KEY (`profesor_encargado_id`) REFERENCES `bs3o8whqnfg4fgedo5fk`.`empleados` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_cursos_jornadas1` FOREIGN KEY (`jornadas_id`) REFERENCES `bs3o8whqnfg4fgedo5fk`.`jornadas` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bs3o8whqnfg4fgedo5fk`.`estudiantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bs3o8whqnfg4fgedo5fk`.`estudiantes` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `nombre` VARCHAR(45) NOT NULL,
    `apellido` VARCHAR(45) NOT NULL,
    `tipos_documentos_id` INT NOT NULL,
    `numero_documento` VARCHAR(45) NOT NULL,
    `fecha_nacimiento` DATE NOT NULL,
    `telefono` VARCHAR(20) NOT NULL,
    `email` VARCHAR(100) NOT NULL,
    `cursos_id` INT NOT NULL,
    PRIMARY KEY (`id`, `tipos_documentos_id`, `cursos_id`),
    UNIQUE INDEX `numero_documento_UNIQUE` (`numero_documento` ASC) VISIBLE,
    INDEX `fk_estudiantes_tipos_documentos1_idx` (`tipos_documentos_id` ASC) VISIBLE,
    INDEX `fk_estudiantes_cursos1_idx` (`cursos_id` ASC) VISIBLE,
    CONSTRAINT `fk_estudiantes_tipos_documentos1` FOREIGN KEY (`tipos_documentos_id`) REFERENCES `bs3o8whqnfg4fgedo5fk`.`tipos_documentos` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_estudiantes_cursos1` FOREIGN KEY (`cursos_id`) REFERENCES `bs3o8whqnfg4fgedo5fk`.`cursos` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bs3o8whqnfg4fgedo5fk`.`cursos_asignaturas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bs3o8whqnfg4fgedo5fk`.`cursos_asignaturas` (
    `id` INT NOT NULL AUTO_INCREMENT,
    `cursos_id` INT NOT NULL,
    `asignaturas_id` INT NOT NULL,
    `profesor_id` INT NOT NULL,
    `intensidad_horaria` INT NOT NULL,
    PRIMARY KEY (
        `id`,
        `cursos_id`,
        `asignaturas_id`,
        `profesor_id`
    ),
    INDEX `fk_cursos_asignaturas_cursos1_idx` (`cursos_id` ASC) VISIBLE,
    INDEX `fk_cursos_asignaturas_asignaturas1_idx` (`asignaturas_id` ASC) VISIBLE,
    INDEX `fk_cursos_asignaturas_empleados1_idx` (`profesor_id` ASC) VISIBLE,
    CONSTRAINT `fk_cursos_asignaturas_cursos1` FOREIGN KEY (`cursos_id`) REFERENCES `bs3o8whqnfg4fgedo5fk`.`cursos` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_cursos_asignaturas_asignaturas1` FOREIGN KEY (`asignaturas_id`) REFERENCES `bs3o8whqnfg4fgedo5fk`.`asignaturas` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
    CONSTRAINT `fk_cursos_asignaturas_empleados1` FOREIGN KEY (`profesor_id`) REFERENCES `bs3o8whqnfg4fgedo5fk`.`empleados` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB;
SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;


-- INSERCIÓN DE  DATOS:

USE `bs3o8whqnfg4fgedo5fk`;

-- INSERT TABLA ESTUDIANTES
INSERT INTO tipos_documentos (nombre, abreviatura) VALUES
('Cédula de Identidad', 'CI'),
('Pasaporte', 'PAS'),
('Licencia de Conducir', 'LC'),
('RUC', 'RUC'),
('Otro', 'OTRO'),
('DIMEX', 'DIMEX'),
('Cédula Extranjería', 'CE');

-- INSERT TABLA ROLES
INSERT INTO roles (nombre) VALUES
('Profesor'),
('Rector'),
('Director'),
('Secretario'),
('Bibliotecario'),
('Contador'),
('Coordinador');

-- INSERT TABLA JORNADAS
INSERT INTO jornadas (nombre, hora_inicio, hora_fin) VALUES
('Mañana', '06:00:00', '12:00:00'),
('Tarde', '013:00:00', '18:00:00');

-- INSERT TABLA ASIGNATURAS
INSERT INTO asignaturas (nombre) VALUES
('Sexto'), ('Séptimo'), ('Octavo'), ('Noveno'), ('Décimo'), ('Once');

-- INSERT TABLA EMPLEADOS
INSERT INTO empleados (nombre, apellido, salario, correo_electronico, tipos_documentos_id, numero_documento, fecha_nacimiento, roles_id) VALUES
('Pedro', 'Jimenez', 2300.00, 'pedro.jimenez@escuela.com', 1, '975243', '1980-05-09', 1),
('Ester', 'Torrez', 1000.00, 'ester.torrez@escuela.com', 2, '680465', '2000-01-08', 1),
('Pedro', 'Rodriguez', 1000.00, 'pedro.rodriguez@escuela.com', 2, '98765432', '2001-03-03', 2),
('Ana', 'Lopez', 1000.00, 'ana.lopez@escuela.com', 2, '10987654', '2002-04-04', 2),
('Luis', 'Hernandez', 1000.00, 'luis.hernandez@escuela.com', 2, '11121314', '2003-05-05', 2),
('Beatriz', 'Diaz', 1000.00, 'beatriz.diaz@escuela.com', 2, '12131415', '2004-06-06', 2),
('Carlos', 'Soto', 1000.00, 'carlos.soto@escuela.com', 2, '13141516', '2005-07-07', 2);

-- INSERT TABLA CURSOS
INSERT INTO cursos (nombre, profesor_encargado_id, jornadas_id) VALUES
('Sexto', 1, 1),
('Séptimo', 5, 1),
('Octavo', 6, 1),
('Noveno', 7, 2),
('Décimo', 8, 2),
('Once', 9, 2);

-- INSERT TABLA CURSOS_ASIGNATURAS
INSERT INTO cursos_asignaturas (cursos_id, asignaturas_id, profesor_id, intensidad_horaria) VALUES
(1, 1, 1, 4),
(1, 2, 2, 4),
(1, 3, 3, 4),
(2, 4, 4, 4),
(2, 5, 2, 4),
(2, 6, 2, 4),
(3, 7, 9, 4),
(3, 1, 5, 4),
(3, 2, 7, 4),
(4, 4, 8, 4),
(4, 5, 7, 4),
(4, 6, 7, 4),
(5, 7, 1, 4),
(5, 1, 5, 4),
(5, 2, 4, 4),
(6, 4, 1, 4),
(6, 5, 2, 4),
(6, 6, 6, 4);

-- INSERT TABLA ESTUDIANTES
INSERT INTO estudiantes (nombre, apellido, tipos_documentos_id, numero_documento, fecha_nacimiento, telefono, email, cursos_id)
VALUES
('Juan', 'Pérez', 1, '123456789', '1998-01-01', '3101234567', 'juan.perez@correo.com', 1),
('María', 'García', 2, '987654323', '2000-02-02', '3112345678', 'maria.garcia@correo.com', 2),
('Pedro', 'López', 3, '876543215', '2002-03-03', '3123456789', 'pedro.lopez@correo.com', 3),
('Ana', 'Martínez', 4, '765432179', '2004-04-04', '3134567890', 'ana.martinez@correo.com', 4),
('Roberto', 'Gómez', 1, '654321098', '2006-05-05', '3145678901', 'roberto.gomez@correo.com', 5),
('Sandra', 'Rodríguez', 2, '543210987', '2008-06-06', '3156789012', 'sandra.rodriguez@correo.com', 1),
('Carlos', 'Muñoz', 3, '432109876', '2010-07-07', '3167890123', 'carlos.munoz@correo.com', 2),
('Diana', 'Fernández', 4, '321098765', '2012-08-08', '3178901234', 'diana.fernandez@correo.com', 3),
('Javier', 'Sánchez', 1, '210987654', '2014-09-09', '3189012345', 'javier.sanchez@correo.com', 4),
('Laura', 'Alvarez', 2, '109876543', '2016-10-10', '3190123456', 'laura.alvarez@correo.com', 5),
('David', 'Ramírez', 3, '987654321', '2018-11-11', '3201234567', 'david.ramirez@correo.com', 1),
('Valentina', 'Flores', 4, '876543210', '2020-12-12', '3212345678', 'valentina.flores@correo.com', 2),
('Andrés', 'González', 1, '765432109', '2022-01-01', '3223456789', 'andres.gonzalez@correo.com', 3);


-- CONSULTAS SOLICITADAS

-- Ver listado de estudiantes de un grupo x.
SELECT e.*,c.nombre FROM estudiantes e
INNER JOIN cursos c
ON e.cursos_id = c.id
WHERE c.id = 1;

-- Ver la lista de estudiantes que vean una asignatura x.
SELECT e.nombre, e.apellido, a.nombre FROM estudiantes e
INNER JOIN cursos_asignaturas cs ON e.cursos_id = cs.cursos_id
INNER JOIN asignaturas a ON cs.asignaturas_id =  a.id
WHERE a.id = 2;

-- Ver la lista de profesores que le dictan clase a un estudiante x.
SELECT prof.nombre, prof.apellido, est.id,est.nombre, est.apellido  FROM empleados prof
INNER JOIN cursos_asignaturas cs ON prof.id = cs.profesor_id
INNER JOIN estudiantes est ON est.cursos_id = cs.cursos_id
WHERE est.id = 37;

-- Ver los grupos ordenados de forma descendente por la cantidad de estudiantes que tiene inscritos.
SELECT COUNT(*) AS Alumnos,c.nombre FROM estudiantes e
INNER JOIN cursos c ON e.cursos_id = c.id
GROUP BY c.nombre ORDER BY Alumnos Desc;